In [1]:
print("Hello World")

Hello World


In [2]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable


## We Are going to learn numpy Now

In [5]:
import numpy as np

In [6]:
arr=np.array([[1,2,3],[4,2,5]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

2

In [9]:
arr.shape

(2, 3)

In [10]:
arr2=np.array([1,3,5])

In [11]:
arr2.shape

(3,)

In [12]:
arr.size

6

In [13]:
arr.dtype

dtype('int32')

In [14]:
a=np.array([[1,2,3],[4,5,6]],dtype='float')

In [15]:
print("Array created using list : \n",a)

Array created using list : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
a=np.array([[1,2,3],[4,5,6]],dtype='int')

In [19]:
print(a)

[[1 2 3]
 [4 5 6]]


In [20]:
b=np.array((1,3,2))
print("\nArray created using passed tuple\n",b)


Array created using passed tuple
 [1 3 2]


In [23]:
#create a constant value array of complex type
c=np.full((3,3),6,dtype='complex')
print("\nAn array initialized with all 6s,Array type is complex\n",c)


An array initialized with all 6s,Array type is complex
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [25]:
#creating a 3*4 array with all zeros
d=np.zeros((3,4))
print("\nArray iniyialized with all zeros:\n",d)


Array iniyialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
#create an array with random values
e=np.random.random((2,2))
print("\nRandom Array:\n",e)


Random Array:
 [[0.09336449 0.48703514]
 [0.32668326 0.83159089]]


In [28]:
#create a sequence of integers from 0 to 30 with space of 5
f=np.arange(0,30,5)
print("\nSequential array with steps of 5:\n",f)


Sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [30]:
#create a sequence of 10 values in range 0 to 5
g=np.linspace(0,5,10)
print("\nA Sequence array with 10 values b/w 0 and 5:\n",g)


A Sequence array with 10 values b/w 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [32]:
#reshaping 3X4 array to 2X3X3 array
arr=np.array([[1,2,3,0],[4,5,6,3],[7,8,9,1]])
new_arr=arr.reshape(2,2,3)
print("\nOriginal array:\n",arr)
print("reshaped array:\n",new_arr)


Original array:
 [[1 2 3 0]
 [4 5 6 3]
 [7 8 9 1]]
reshaped array:
 [[[1 2 3]
  [0 4 5]]

 [[6 3 7]
  [8 9 1]]]


In [37]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.arange?
#help

In [40]:
np.eye?

In [41]:
#flatten array
arr=np.array([[1,2,3],[4,5,6]])
flarr=arr.flatten()
print("\nOriginal Array:\n",arr)
print("\nFattened Array:\n",flarr)


Original Array:
 [[1 2 3]
 [4 5 6]]

Fattened Array:
 [1 2 3 4 5 6]


# Slicing

In [42]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2,6,7,8],[3,-7,4,2]])

In [43]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2. ,  6. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [44]:
temp=arr[:2,::2]
print("Array with first 2 rows and alternate column(0 and 2):\n",temp)

Array with first 2 rows and alternate column(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [45]:
arr[1:,:3]

array([[ 4. , -0.5,  6. ],
       [ 2. ,  6. ,  7. ],
       [ 3. , -7. ,  4. ]])

In [46]:
#integer array indexing example
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):\n",temp)


Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 6. 3.]


In [50]:
#boolean array indexing example
cond=arr>0 
temp=arr[cond]
print("\nElements greater than 0:\n",temp)


Elements greater than 0:
 [2. 4. 4. 6. 2. 6. 7. 8. 3. 4. 2.]


In [51]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2. ,  6. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [52]:
#Transpose
arr.T

array([[-1. ,  4. ,  2. ,  3. ],
       [ 2. , -0.5,  6. , -7. ],
       [ 0. ,  6. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  2. ]])

In [53]:
arr.max()

8.0

In [54]:
arr.max(axis=1)

array([4., 6., 8., 4.])

In [55]:
arr.min(axis=0)

array([-1., -7.,  0.,  0.])

In [56]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [57]:
#vertical stacking
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
#horizontal stacking
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [63]:
c=[5,6]

In [65]:
#stacking columns
np.column_stack((a,c))

array([[1, 2, 5],
       [3, 4, 6]])

In [66]:
#concatenating
np.concatenate((a,b),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [67]:
np.hsplit(a,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [68]:
np.vsplit(a,2)

[array([[1, 2]]), array([[3, 4]])]